package lime;


import lime.utils.Assets;


class AssetData {

	private static var initialized:Bool = false;
	
	public static var library = new #if haxe3 Map <String, #else Hash <#end LibraryType> ();
	public static var path = new #if haxe3 Map <String, #else Hash <#end String> ();
	public static var type = new #if haxe3 Map <String, #else Hash <#end AssetType> ();	
	
	public static function initialize():Void {
		
		if (!initialized) {
			
			path.set ("assets/data/BaseMap.oel", "assets/data/BaseMap.oel");
			type.set ("assets/data/BaseMap.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/basemap1.oel", "assets/data/basemap1.oel");
			type.set ("assets/data/basemap1.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/basemap2.oel", "assets/data/basemap2.oel");
			type.set ("assets/data/basemap2.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/data-goes-here.txt", "assets/data/data-goes-here.txt");
			type.set ("assets/data/data-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/Final Maps/worldmap1.oel", "assets/data/Final Maps/worldmap1.oel");
			type.set ("assets/data/Final Maps/worldmap1.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/Final Maps/worldmap2.oel", "assets/data/Final Maps/worldmap2.oel");
			type.set ("assets/data/Final Maps/worldmap2.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/kid_dad-testing.oel", "assets/data/kid_dad-testing.oel");
			type.set ("assets/data/kid_dad-testing.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/level_1.oel", "assets/data/level_1.oel");
			type.set ("assets/data/level_1.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/level_2.oel", "assets/data/level_2.oel");
			type.set ("assets/data/level_2.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/level_3.oel", "assets/data/level_3.oel");
			type.set ("assets/data/level_3.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/level_4.oel", "assets/data/level_4.oel");
			type.set ("assets/data/level_4.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/Mission1.oel", "assets/data/Mission1.oel");
			type.set ("assets/data/Mission1.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/Mission1_0.oel", "assets/data/Mission1_0.oel");
			type.set ("assets/data/Mission1_0.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/Mission1_1.oel", "assets/data/Mission1_1.oel");
			type.set ("assets/data/Mission1_1.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/reachtshelden.oep", "assets/data/reachtshelden.oep");
			type.set ("assets/data/reachtshelden.oep", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/room-001.oel", "assets/data/room-001.oel");
			type.set ("assets/data/room-001.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/testingmap.oel", "assets/data/testingmap.oel");
			type.set ("assets/data/testingmap.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/female/kind2-1.mp3", "assets/female/kind2-1.mp3");
			type.set ("assets/female/kind2-1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/female/kind2-2.mp3", "assets/female/kind2-2.mp3");
			type.set ("assets/female/kind2-2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/female/moeder1.mp3", "assets/female/moeder1.mp3");
			type.set ("assets/female/moeder1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/female/moeder2.mp3", "assets/female/moeder2.mp3");
			type.set ("assets/female/moeder2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/images/1StartingScreeeeeeen.png", "assets/images/1StartingScreeeeeeen.png");
			type.set ("assets/images/1StartingScreeeeeeen.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/AngryDadMission2.png", "assets/images/AngryDadMission2.png");
			type.set ("assets/images/AngryDadMission2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/AsianDad.png", "assets/images/AsianDad.png");
			type.set ("assets/images/AsianDad.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/AsianDad.psd", "assets/images/AsianDad.psd");
			type.set ("assets/images/AsianDad.psd", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/Attack128x64.png", "assets/images/Attack128x64.png");
			type.set ("assets/images/Attack128x64.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Bald-Mission1.png", "assets/images/Bald-Mission1.png");
			type.set ("assets/images/Bald-Mission1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Bald-Mission1.psd", "assets/images/Bald-Mission1.psd");
			type.set ("assets/images/Bald-Mission1.psd", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/BaldMission1.png", "assets/images/BaldMission1.png");
			type.set ("assets/images/BaldMission1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Banner.psd", "assets/images/Banner.psd");
			type.set ("assets/images/Banner.psd", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/BeachBall-Mission3.png", "assets/images/BeachBall-Mission3.png");
			type.set ("assets/images/BeachBall-Mission3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/bigass HOUSE.png", "assets/images/bigass HOUSE.png");
			type.set ("assets/images/bigass HOUSE.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/button.png", "assets/images/button.png");
			type.set ("assets/images/button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/CharacterTilesheet768x768.png", "assets/images/CharacterTilesheet768x768.png");
			type.set ("assets/images/CharacterTilesheet768x768.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/coin.png", "assets/images/coin.png");
			type.set ("assets/images/coin.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/CollectingSpirit Kopie.png", "assets/images/CollectingSpirit Kopie.png");
			type.set ("assets/images/CollectingSpirit Kopie.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/DodgeBall-Mission-3.png", "assets/images/DodgeBall-Mission-3.png");
			type.set ("assets/images/DodgeBall-Mission-3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Emo-Kid-Mission2 (1).png", "assets/images/Emo-Kid-Mission2 (1).png");
			type.set ("assets/images/Emo-Kid-Mission2 (1).png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Emo-Kid-Mission3).png", "assets/images/Emo-Kid-Mission3).png");
			type.set ("assets/images/Emo-Kid-Mission3).png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/EmoKidMission2.png", "assets/images/EmoKidMission2.png");
			type.set ("assets/images/EmoKidMission2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/emokidMission3.png", "assets/images/emokidMission3.png");
			type.set ("assets/images/emokidMission3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/enemy-0.png", "assets/images/enemy-0.png");
			type.set ("assets/images/enemy-0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/enemy-1.png", "assets/images/enemy-1.png");
			type.set ("assets/images/enemy-1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/enemy-2.png", "assets/images/enemy-2.png");
			type.set ("assets/images/enemy-2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/feggit.png", "assets/images/feggit.png");
			type.set ("assets/images/feggit.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/floor.png", "assets/images/floor.png");
			type.set ("assets/images/floor.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Football-Mission-3.png", "assets/images/Football-Mission-3.png");
			type.set ("assets/images/Football-Mission-3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Furniture.png", "assets/images/Furniture.png");
			type.set ("assets/images/Furniture.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Girl-Mission1.png", "assets/images/Girl-Mission1.png");
			type.set ("assets/images/Girl-Mission1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/girlMission1.png", "assets/images/girlMission1.png");
			type.set ("assets/images/girlMission1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/HATSNewRoadTiles.png", "assets/images/HATSNewRoadTiles.png");
			type.set ("assets/images/HATSNewRoadTiles.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/HATSNewRoadTiles.psd", "assets/images/HATSNewRoadTiles.psd");
			type.set ("assets/images/HATSNewRoadTiles.psd", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/health.png", "assets/images/health.png");
			type.set ("assets/images/health.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/HOLE.png", "assets/images/HOLE.png");
			type.set ("assets/images/HOLE.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/HOUSE.psd", "assets/images/HOUSE.psd");
			type.set ("assets/images/HOUSE.psd", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/images-go-here.txt", "assets/images/images-go-here.txt");
			type.set ("assets/images/images-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/ion.png", "assets/images/ion.png");
			type.set ("assets/images/ion.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Judge-Mission-3.png", "assets/images/Judge-Mission-3.png");
			type.set ("assets/images/Judge-Mission-3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Judge.png", "assets/images/Judge.png");
			type.set ("assets/images/Judge.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind1.1.png", "assets/images/kind1.1.png");
			type.set ("assets/images/kind1.1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind1.2.png", "assets/images/kind1.2.png");
			type.set ("assets/images/kind1.2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind1.3.png", "assets/images/kind1.3.png");
			type.set ("assets/images/kind1.3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind1.4.png", "assets/images/kind1.4.png");
			type.set ("assets/images/kind1.4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind1.5.png", "assets/images/kind1.5.png");
			type.set ("assets/images/kind1.5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind2.1.png", "assets/images/kind2.1.png");
			type.set ("assets/images/kind2.1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind2.2.png", "assets/images/kind2.2.png");
			type.set ("assets/images/kind2.2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind2.3.png", "assets/images/kind2.3.png");
			type.set ("assets/images/kind2.3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind2.4.png", "assets/images/kind2.4.png");
			type.set ("assets/images/kind2.4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind2.5.png", "assets/images/kind2.5.png");
			type.set ("assets/images/kind2.5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind3.1.png", "assets/images/kind3.1.png");
			type.set ("assets/images/kind3.1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind3.2.png", "assets/images/kind3.2.png");
			type.set ("assets/images/kind3.2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind3.3.png", "assets/images/kind3.3.png");
			type.set ("assets/images/kind3.3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind3.4.png", "assets/images/kind3.4.png");
			type.set ("assets/images/kind3.4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind3.5.png", "assets/images/kind3.5.png");
			type.set ("assets/images/kind3.5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind3.6.png", "assets/images/kind3.6.png");
			type.set ("assets/images/kind3.6.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/kind3.7.png", "assets/images/kind3.7.png");
			type.set ("assets/images/kind3.7.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/KJRW-Tutotial-3.png", "assets/images/KJRW-Tutotial-3.png");
			type.set ("assets/images/KJRW-Tutotial-3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Knightmare Fight/Text1.png", "assets/images/Knightmare Fight/Text1.png");
			type.set ("assets/images/Knightmare Fight/Text1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Knightmare.png", "assets/images/Knightmare.png");
			type.set ("assets/images/Knightmare.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/KnightmareAttackTilesheet.png", "assets/images/KnightmareAttackTilesheet.png");
			type.set ("assets/images/KnightmareAttackTilesheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/KnightmareCompleteTilesheet.png", "assets/images/KnightmareCompleteTilesheet.png");
			type.set ("assets/images/KnightmareCompleteTilesheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/KnightmareDash.png", "assets/images/KnightmareDash.png");
			type.set ("assets/images/KnightmareDash.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/KnightmareShield4.png", "assets/images/KnightmareShield4.png");
			type.set ("assets/images/KnightmareShield4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/KnightmareText.png", "assets/images/KnightmareText.png");
			type.set ("assets/images/KnightmareText.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/KRJW-Tutorial.png", "assets/images/KRJW-Tutorial.png");
			type.set ("assets/images/KRJW-Tutorial.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/KRJW-Tutorial.psd", "assets/images/KRJW-Tutorial.psd");
			type.set ("assets/images/KRJW-Tutorial.psd", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/Missie1/intromissie1/prof0.png", "assets/images/Missie1/intromissie1/prof0.png");
			type.set ("assets/images/Missie1/intromissie1/prof0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie1/intromissie1/prof1.png", "assets/images/Missie1/intromissie1/prof1.png");
			type.set ("assets/images/Missie1/intromissie1/prof1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie1/intromissie1/prof2.png", "assets/images/Missie1/intromissie1/prof2.png");
			type.set ("assets/images/Missie1/intromissie1/prof2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie1/intromissie1/prof3.png", "assets/images/Missie1/intromissie1/prof3.png");
			type.set ("assets/images/Missie1/intromissie1/prof3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie1/intromissie1/prof4.png", "assets/images/Missie1/intromissie1/prof4.png");
			type.set ("assets/images/Missie1/intromissie1/prof4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie1/intromissie1/prof5.png", "assets/images/Missie1/intromissie1/prof5.png");
			type.set ("assets/images/Missie1/intromissie1/prof5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie1/intromissie1/prof6.png", "assets/images/Missie1/intromissie1/prof6.png");
			type.set ("assets/images/Missie1/intromissie1/prof6.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie2/emo1.1.png", "assets/images/Missie2/emo1.1.png");
			type.set ("assets/images/Missie2/emo1.1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie2/emo1.10.png", "assets/images/Missie2/emo1.10.png");
			type.set ("assets/images/Missie2/emo1.10.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie2/emo1.11.png", "assets/images/Missie2/emo1.11.png");
			type.set ("assets/images/Missie2/emo1.11.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie2/emo1.2.png", "assets/images/Missie2/emo1.2.png");
			type.set ("assets/images/Missie2/emo1.2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie2/emo1.3.png", "assets/images/Missie2/emo1.3.png");
			type.set ("assets/images/Missie2/emo1.3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie2/emo1.4.png", "assets/images/Missie2/emo1.4.png");
			type.set ("assets/images/Missie2/emo1.4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie2/emo1.5.png", "assets/images/Missie2/emo1.5.png");
			type.set ("assets/images/Missie2/emo1.5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie2/emo1.6.png", "assets/images/Missie2/emo1.6.png");
			type.set ("assets/images/Missie2/emo1.6.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie2/emo1.7.png", "assets/images/Missie2/emo1.7.png");
			type.set ("assets/images/Missie2/emo1.7.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie2/emo1.8.png", "assets/images/Missie2/emo1.8.png");
			type.set ("assets/images/Missie2/emo1.8.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie2/emo1.9.png", "assets/images/Missie2/emo1.9.png");
			type.set ("assets/images/Missie2/emo1.9.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Feggit1.png", "assets/images/Missie3/Feggit1.png");
			type.set ("assets/images/Missie3/Feggit1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Feggit2.png", "assets/images/Missie3/Feggit2.png");
			type.set ("assets/images/Missie3/Feggit2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Feggit3.png", "assets/images/Missie3/Feggit3.png");
			type.set ("assets/images/Missie3/Feggit3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Feggit4.png", "assets/images/Missie3/Feggit4.png");
			type.set ("assets/images/Missie3/Feggit4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Feggit5.png", "assets/images/Missie3/Feggit5.png");
			type.set ("assets/images/Missie3/Feggit5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Judge1.png", "assets/images/Missie3/Judge1.png");
			type.set ("assets/images/Missie3/Judge1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Judge2.png", "assets/images/Missie3/Judge2.png");
			type.set ("assets/images/Missie3/Judge2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Mom1.png", "assets/images/Missie3/Mom1.png");
			type.set ("assets/images/Missie3/Mom1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Mom2.png", "assets/images/Missie3/Mom2.png");
			type.set ("assets/images/Missie3/Mom2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Mom3.png", "assets/images/Missie3/Mom3.png");
			type.set ("assets/images/Missie3/Mom3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Pro1.png", "assets/images/Missie3/Pro1.png");
			type.set ("assets/images/Missie3/Pro1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Pro2.png", "assets/images/Missie3/Pro2.png");
			type.set ("assets/images/Missie3/Pro2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Pro3.png", "assets/images/Missie3/Pro3.png");
			type.set ("assets/images/Missie3/Pro3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Pro4.png", "assets/images/Missie3/Pro4.png");
			type.set ("assets/images/Missie3/Pro4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Pro5.png", "assets/images/Missie3/Pro5.png");
			type.set ("assets/images/Missie3/Pro5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Pro6.png", "assets/images/Missie3/Pro6.png");
			type.set ("assets/images/Missie3/Pro6.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Pro7.png", "assets/images/Missie3/Pro7.png");
			type.set ("assets/images/Missie3/Pro7.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Pro8.png", "assets/images/Missie3/Pro8.png");
			type.set ("assets/images/Missie3/Pro8.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Prof9.png", "assets/images/Missie3/Prof9.png");
			type.set ("assets/images/Missie3/Prof9.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Missie3/Thumbs2.db", "assets/images/Missie3/Thumbs2.db");
			type.set ("assets/images/Missie3/Thumbs2.db", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/Mission1Girl.png", "assets/images/Mission1Girl.png");
			type.set ("assets/images/Mission1Girl.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Mission2Football.png", "assets/images/Mission2Football.png");
			type.set ("assets/images/Mission2Football.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Mission3 Dodgeball.png", "assets/images/Mission3 Dodgeball.png");
			type.set ("assets/images/Mission3 Dodgeball.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Mission3 Dodgeball.psd", "assets/images/Mission3 Dodgeball.psd");
			type.set ("assets/images/Mission3 Dodgeball.psd", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/Mission3-Mother.png", "assets/images/Mission3-Mother.png");
			type.set ("assets/images/Mission3-Mother.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Mission3Kid1.png", "assets/images/Mission3Kid1.png");
			type.set ("assets/images/Mission3Kid1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Mission3Kid2.png", "assets/images/Mission3Kid2.png");
			type.set ("assets/images/Mission3Kid2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Mission3Kid3.png", "assets/images/Mission3Kid3.png");
			type.set ("assets/images/Mission3Kid3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Mission3Kid4.png", "assets/images/Mission3Kid4.png");
			type.set ("assets/images/Mission3Kid4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Mission3Kid5.png", "assets/images/Mission3Kid5.png");
			type.set ("assets/images/Mission3Kid5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Mission3Kid6.png", "assets/images/Mission3Kid6.png");
			type.set ("assets/images/Mission3Kid6.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Mom.png", "assets/images/Mom.png");
			type.set ("assets/images/Mom.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Mother-Mission-3.psd", "assets/images/Mother-Mission-3.psd");
			type.set ("assets/images/Mother-Mission-3.psd", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/NEWTilesheet_Complete.png", "assets/images/NEWTilesheet_Complete.png");
			type.set ("assets/images/NEWTilesheet_Complete.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/NEW_Tilesheet_Complete.png", "assets/images/NEW_Tilesheet_Complete.png");
			type.set ("assets/images/NEW_Tilesheet_Complete.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/NEW_Tilesheet_Complete.psd", "assets/images/NEW_Tilesheet_Complete.psd");
			type.set ("assets/images/NEW_Tilesheet_Complete.psd", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/NPCCharacterTilesheet.png", "assets/images/NPCCharacterTilesheet.png");
			type.set ("assets/images/NPCCharacterTilesheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pat.png", "assets/images/pat.png");
			type.set ("assets/images/pat.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/player.png", "assets/images/player.png");
			type.set ("assets/images/player.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pointer.png", "assets/images/pointer.png");
			type.set ("assets/images/pointer.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Principle.png", "assets/images/Principle.png");
			type.set ("assets/images/Principle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Principle.psd", "assets/images/Principle.psd");
			type.set ("assets/images/Principle.psd", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/resetbutton.png", "assets/images/resetbutton.png");
			type.set ("assets/images/resetbutton.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/SChool modified.png", "assets/images/SChool modified.png");
			type.set ("assets/images/SChool modified.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Speechbubble.png", "assets/images/Speechbubble.png");
			type.set ("assets/images/Speechbubble.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Speechbubble.psd", "assets/images/Speechbubble.psd");
			type.set ("assets/images/Speechbubble.psd", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/Starting Screen.jpg", "assets/images/Starting Screen.jpg");
			type.set ("assets/images/Starting Screen.jpg", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Story/1.png", "assets/images/Story/1.png");
			type.set ("assets/images/Story/1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Story/2.png", "assets/images/Story/2.png");
			type.set ("assets/images/Story/2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Story/3.png", "assets/images/Story/3.png");
			type.set ("assets/images/Story/3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Story/4.png", "assets/images/Story/4.png");
			type.set ("assets/images/Story/4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Story/Introscreen.png", "assets/images/Story/Introscreen.png");
			type.set ("assets/images/Story/Introscreen.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Story/Pat.png", "assets/images/Story/Pat.png");
			type.set ("assets/images/Story/Pat.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Story/Prof.png", "assets/images/Story/Prof.png");
			type.set ("assets/images/Story/Prof.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Story/Tec.png", "assets/images/Story/Tec.png");
			type.set ("assets/images/Story/Tec.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/street.PNG", "assets/images/street.PNG");
			type.set ("assets/images/street.PNG", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/SWAG-Kid-Walk-Kopie.png", "assets/images/SWAG-Kid-Walk-Kopie.png");
			type.set ("assets/images/SWAG-Kid-Walk-Kopie.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Swagkid.png", "assets/images/Swagkid.png");
			type.set ("assets/images/Swagkid.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/SwagKidMission1.png", "assets/images/SwagKidMission1.png");
			type.set ("assets/images/SwagKidMission1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Teacher.png", "assets/images/Teacher.png");
			type.set ("assets/images/Teacher.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/teacher1.png", "assets/images/teacher1.png");
			type.set ("assets/images/teacher1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tec.png", "assets/images/tec.png");
			type.set ("assets/images/tec.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Thumbs3.db", "assets/images/Thumbs3.db");
			type.set ("assets/images/Thumbs3.db", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/tiles.png", "assets/images/tiles.png");
			type.set ("assets/images/tiles.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Tilesheet_Complete.png", "assets/images/Tilesheet_Complete.png");
			type.set ("assets/images/Tilesheet_Complete.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Tilesheet_Complete.psd", "assets/images/Tilesheet_Complete.psd");
			type.set ("assets/images/Tilesheet_Complete.psd", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/Wall.psd", "assets/images/Wall.psd");
			type.set ("assets/images/Wall.psd", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/images/WallKJRW.png", "assets/images/WallKJRW.png");
			type.set ("assets/images/WallKJRW.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/music/music-goes-here.txt", "assets/music/music-goes-here.txt");
			type.set ("assets/music/music-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/music/select.wav", "assets/music/select.wav");
			type.set ("assets/music/select.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/music/townMusic.wav", "assets/music/townMusic.wav");
			type.set ("assets/music/townMusic.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/dooropening.mp3", "assets/sounds/Abilities/dooropening.mp3");
			type.set ("assets/sounds/Abilities/dooropening.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Heal.mp3", "assets/sounds/Abilities/Heal.mp3");
			type.set ("assets/sounds/Abilities/Heal.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Heal1.mp3", "assets/sounds/Abilities/Heal1.mp3");
			type.set ("assets/sounds/Abilities/Heal1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/PatIndoor.mp3", "assets/sounds/Abilities/PatIndoor.mp3");
			type.set ("assets/sounds/Abilities/PatIndoor.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/PatIndoor2.mp3", "assets/sounds/Abilities/PatIndoor2.mp3");
			type.set ("assets/sounds/Abilities/PatIndoor2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/PatKnigthmare.mp3", "assets/sounds/Abilities/PatKnigthmare.mp3");
			type.set ("assets/sounds/Abilities/PatKnigthmare.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/PatKnigthmare1.mp3", "assets/sounds/Abilities/PatKnigthmare1.mp3");
			type.set ("assets/sounds/Abilities/PatKnigthmare1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/PatOutdoor.mp3", "assets/sounds/Abilities/PatOutdoor.mp3");
			type.set ("assets/sounds/Abilities/PatOutdoor.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/PatOutdoor1.mp3", "assets/sounds/Abilities/PatOutdoor1.mp3");
			type.set ("assets/sounds/Abilities/PatOutdoor1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Shield.mp3", "assets/sounds/Abilities/Shield.mp3");
			type.set ("assets/sounds/Abilities/Shield.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Shield1.mp3", "assets/sounds/Abilities/Shield1.mp3");
			type.set ("assets/sounds/Abilities/Shield1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/1.mp3", "assets/sounds/Abilities/Source/1.mp3");
			type.set ("assets/sounds/Abilities/Source/1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/2.mp3", "assets/sounds/Abilities/Source/2.mp3");
			type.set ("assets/sounds/Abilities/Source/2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/3.mp3", "assets/sounds/Abilities/Source/3.mp3");
			type.set ("assets/sounds/Abilities/Source/3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/Heal.wav", "assets/sounds/Abilities/Source/Heal.wav");
			type.set ("assets/sounds/Abilities/Source/Heal.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/Heal1.wav", "assets/sounds/Abilities/Source/Heal1.wav");
			type.set ("assets/sounds/Abilities/Source/Heal1.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/Hit_Hurt18.wav", "assets/sounds/Abilities/Source/Hit_Hurt18.wav");
			type.set ("assets/sounds/Abilities/Source/Hit_Hurt18.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/Hit_Hurt32.wav", "assets/sounds/Abilities/Source/Hit_Hurt32.wav");
			type.set ("assets/sounds/Abilities/Source/Hit_Hurt32.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/JUDGE-O-METERCOIN.wav", "assets/sounds/Abilities/Source/JUDGE-O-METERCOIN.wav");
			type.set ("assets/sounds/Abilities/Source/JUDGE-O-METERCOIN.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/Push.wav", "assets/sounds/Abilities/Source/Push.wav");
			type.set ("assets/sounds/Abilities/Source/Push.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/Push1.wav", "assets/sounds/Abilities/Source/Push1.wav");
			type.set ("assets/sounds/Abilities/Source/Push1.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/Shield1.wav", "assets/sounds/Abilities/Source/Shield1.wav");
			type.set ("assets/sounds/Abilities/Source/Shield1.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/switch.mp3", "assets/sounds/Abilities/switch.mp3");
			type.set ("assets/sounds/Abilities/switch.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Game/JUDGE-O-METERCOIN.mp3", "assets/sounds/Game/JUDGE-O-METERCOIN.mp3");
			type.set ("assets/sounds/Game/JUDGE-O-METERCOIN.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Game/select-1.wav", "assets/sounds/Game/select-1.wav");
			type.set ("assets/sounds/Game/select-1.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Gesprek1.wav", "assets/sounds/Gesprek1.wav");
			type.set ("assets/sounds/Gesprek1.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/IntroMissie/1IntroPijltjestoetsen.mp3", "assets/sounds/IntroMissie/1IntroPijltjestoetsen.mp3");
			type.set ("assets/sounds/IntroMissie/1IntroPijltjestoetsen.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/IntroMissie/2GoedGedaan.mp3", "assets/sounds/IntroMissie/2GoedGedaan.mp3");
			type.set ("assets/sounds/IntroMissie/2GoedGedaan.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/IntroMissie/3PatInstructie.mp3", "assets/sounds/IntroMissie/3PatInstructie.mp3");
			type.set ("assets/sounds/IntroMissie/3PatInstructie.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/IntroMissie/4TecInstructie1.mp3", "assets/sounds/IntroMissie/4TecInstructie1.mp3");
			type.set ("assets/sounds/IntroMissie/4TecInstructie1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/IntroMissie/5TecInstructie2.mp3", "assets/sounds/IntroMissie/5TecInstructie2.mp3");
			type.set ("assets/sounds/IntroMissie/5TecInstructie2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/IntroMissie/6ProfInstructie.mp3", "assets/sounds/IntroMissie/6ProfInstructie.mp3");
			type.set ("assets/sounds/IntroMissie/6ProfInstructie.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/IntroMissie/7IntroOutro.mp3", "assets/sounds/IntroMissie/7IntroOutro.mp3");
			type.set ("assets/sounds/IntroMissie/7IntroOutro.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/IntroVoice.mp3", "assets/sounds/IntroVoice.mp3");
			type.set ("assets/sounds/IntroVoice.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Knightmare/Knightmare1.mp3", "assets/sounds/Knightmare/Knightmare1.mp3");
			type.set ("assets/sounds/Knightmare/Knightmare1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Knightmare/Knightmare2.mp3", "assets/sounds/Knightmare/Knightmare2.mp3");
			type.set ("assets/sounds/Knightmare/Knightmare2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Knightmare/Knightmare3.mp3", "assets/sounds/Knightmare/Knightmare3.mp3");
			type.set ("assets/sounds/Knightmare/Knightmare3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Knightmare/Knightmare4.mp3", "assets/sounds/Knightmare/Knightmare4.mp3");
			type.set ("assets/sounds/Knightmare/Knightmare4.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Knightmare/Knightmare5.mp3", "assets/sounds/Knightmare/Knightmare5.mp3");
			type.set ("assets/sounds/Knightmare/Knightmare5.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Knightmare/Knightmare6.mp3", "assets/sounds/Knightmare/Knightmare6.mp3");
			type.set ("assets/sounds/Knightmare/Knightmare6.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Knightmare/Knightmare7.mp3", "assets/sounds/Knightmare/Knightmare7.mp3");
			type.set ("assets/sounds/Knightmare/Knightmare7.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Knightmare/Knightmare8.mp3", "assets/sounds/Knightmare/Knightmare8.mp3");
			type.set ("assets/sounds/Knightmare/Knightmare8.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind1/Kind1-1.mp3", "assets/sounds/Missie1/Kind1/Kind1-1.mp3");
			type.set ("assets/sounds/Missie1/Kind1/Kind1-1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind1/Kind1-2.mp3", "assets/sounds/Missie1/Kind1/Kind1-2.mp3");
			type.set ("assets/sounds/Missie1/Kind1/Kind1-2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind1/Prof1-4.mp3", "assets/sounds/Missie1/Kind1/Prof1-4.mp3");
			type.set ("assets/sounds/Missie1/Kind1/Prof1-4.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind1/Prof2-4.mp3", "assets/sounds/Missie1/Kind1/Prof2-4.mp3");
			type.set ("assets/sounds/Missie1/Kind1/Prof2-4.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind1/Prof3-4.mp3", "assets/sounds/Missie1/Kind1/Prof3-4.mp3");
			type.set ("assets/sounds/Missie1/Kind1/Prof3-4.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind2/Prof1-1.mp3", "assets/sounds/Missie1/Kind2/Prof1-1.mp3");
			type.set ("assets/sounds/Missie1/Kind2/Prof1-1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind2/Prof2-1.mp3", "assets/sounds/Missie1/Kind2/Prof2-1.mp3");
			type.set ("assets/sounds/Missie1/Kind2/Prof2-1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind2/Prof3-1.mp3", "assets/sounds/Missie1/Kind2/Prof3-1.mp3");
			type.set ("assets/sounds/Missie1/Kind2/Prof3-1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind3/Kind3-1.mp3", "assets/sounds/Missie1/Kind3/Kind3-1.mp3");
			type.set ("assets/sounds/Missie1/Kind3/Kind3-1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind3/Kind3-2.mp3", "assets/sounds/Missie1/Kind3/Kind3-2.mp3");
			type.set ("assets/sounds/Missie1/Kind3/Kind3-2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind3/Kind3-3.mp3", "assets/sounds/Missie1/Kind3/Kind3-3.mp3");
			type.set ("assets/sounds/Missie1/Kind3/Kind3-3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind3/Prof1-2.mp3", "assets/sounds/Missie1/Kind3/Prof1-2.mp3");
			type.set ("assets/sounds/Missie1/Kind3/Prof1-2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind3/Prof2-2.mp3", "assets/sounds/Missie1/Kind3/Prof2-2.mp3");
			type.set ("assets/sounds/Missie1/Kind3/Prof2-2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind3/Prof3-2.mp3", "assets/sounds/Missie1/Kind3/Prof3-2.mp3");
			type.set ("assets/sounds/Missie1/Kind3/Prof3-2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind3/Prof4-2.mp3", "assets/sounds/Missie1/Kind3/Prof4-2.mp3");
			type.set ("assets/sounds/Missie1/Kind3/Prof4-2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Prof4-3.mp3", "assets/sounds/Missie1/Prof4-3.mp3");
			type.set ("assets/sounds/Missie1/Prof4-3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Teacher/Prof1-3.mp3", "assets/sounds/Missie1/Teacher/Prof1-3.mp3");
			type.set ("assets/sounds/Missie1/Teacher/Prof1-3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Teacher/Prof2-3.mp3", "assets/sounds/Missie1/Teacher/Prof2-3.mp3");
			type.set ("assets/sounds/Missie1/Teacher/Prof2-3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Teacher/Prof3-3.mp3", "assets/sounds/Missie1/Teacher/Prof3-3.mp3");
			type.set ("assets/sounds/Missie1/Teacher/Prof3-3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Teacher/Teacher1-1.mp3", "assets/sounds/Missie1/Teacher/Teacher1-1.mp3");
			type.set ("assets/sounds/Missie1/Teacher/Teacher1-1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Teacher/Teacher1-2.mp3", "assets/sounds/Missie1/Teacher/Teacher1-2.mp3");
			type.set ("assets/sounds/Missie1/Teacher/Teacher1-2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Teacher/Teacher1-3.mp3", "assets/sounds/Missie1/Teacher/Teacher1-3.mp3");
			type.set ("assets/sounds/Missie1/Teacher/Teacher1-3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Teacher/Teacher1-4.mp3", "assets/sounds/Missie1/Teacher/Teacher1-4.mp3");
			type.set ("assets/sounds/Missie1/Teacher/Teacher1-4.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Teacher/Teacher1.mp3", "assets/sounds/Missie1/Teacher/Teacher1.mp3");
			type.set ("assets/sounds/Missie1/Teacher/Teacher1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Dad1.mp3", "assets/sounds/Missie2/Dad1.mp3");
			type.set ("assets/sounds/Missie2/Dad1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Dad2.mp3", "assets/sounds/Missie2/Dad2.mp3");
			type.set ("assets/sounds/Missie2/Dad2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Dad3.mp3", "assets/sounds/Missie2/Dad3.mp3");
			type.set ("assets/sounds/Missie2/Dad3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Kid1.mp3", "assets/sounds/Missie2/Kid1.mp3");
			type.set ("assets/sounds/Missie2/Kid1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Kid2.mp3", "assets/sounds/Missie2/Kid2.mp3");
			type.set ("assets/sounds/Missie2/Kid2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Kid3.mp3", "assets/sounds/Missie2/Kid3.mp3");
			type.set ("assets/sounds/Missie2/Kid3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Prof1.mp3", "assets/sounds/Missie2/Prof1.mp3");
			type.set ("assets/sounds/Missie2/Prof1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Prof2.mp3", "assets/sounds/Missie2/Prof2.mp3");
			type.set ("assets/sounds/Missie2/Prof2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Prof3.mp3", "assets/sounds/Missie2/Prof3.mp3");
			type.set ("assets/sounds/Missie2/Prof3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Prof4.mp3", "assets/sounds/Missie2/Prof4.mp3");
			type.set ("assets/sounds/Missie2/Prof4.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Prof5.mp3", "assets/sounds/Missie2/Prof5.mp3");
			type.set ("assets/sounds/Missie2/Prof5.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie3/Missie3-1.mp3", "assets/sounds/Missie3/Missie3-1.mp3");
			type.set ("assets/sounds/Missie3/Missie3-1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie3/Missie3-10.mp3", "assets/sounds/Missie3/Missie3-10.mp3");
			type.set ("assets/sounds/Missie3/Missie3-10.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie3/Missie3-12.mp3", "assets/sounds/Missie3/Missie3-12.mp3");
			type.set ("assets/sounds/Missie3/Missie3-12.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie3/Missie3-14.mp3", "assets/sounds/Missie3/Missie3-14.mp3");
			type.set ("assets/sounds/Missie3/Missie3-14.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie3/Missie3-15.mp3", "assets/sounds/Missie3/Missie3-15.mp3");
			type.set ("assets/sounds/Missie3/Missie3-15.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie3/Missie3-2.mp3", "assets/sounds/Missie3/Missie3-2.mp3");
			type.set ("assets/sounds/Missie3/Missie3-2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie3/Missie3-3.mp3", "assets/sounds/Missie3/Missie3-3.mp3");
			type.set ("assets/sounds/Missie3/Missie3-3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie3/Missie3-4.mp3", "assets/sounds/Missie3/Missie3-4.mp3");
			type.set ("assets/sounds/Missie3/Missie3-4.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie3/Missie3-5.mp3", "assets/sounds/Missie3/Missie3-5.mp3");
			type.set ("assets/sounds/Missie3/Missie3-5.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie3/Missie3-6.mp3", "assets/sounds/Missie3/Missie3-6.mp3");
			type.set ("assets/sounds/Missie3/Missie3-6.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie3/Missie3-7.mp3", "assets/sounds/Missie3/Missie3-7.mp3");
			type.set ("assets/sounds/Missie3/Missie3-7.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie3/Missie3-8.mp3", "assets/sounds/Missie3/Missie3-8.mp3");
			type.set ("assets/sounds/Missie3/Missie3-8.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Music/Chase.mp3", "assets/sounds/Music/Chase.mp3");
			type.set ("assets/sounds/Music/Chase.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Music/Haahn's Dutch.wav", "assets/sounds/Music/Haahn's Dutch.wav");
			type.set ("assets/sounds/Music/Haahn's Dutch.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Music/Lab Junk.wav", "assets/sounds/Music/Lab Junk.wav");
			type.set ("assets/sounds/Music/Lab Junk.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Music/Puzzle.mp3", "assets/sounds/Music/Puzzle.mp3");
			type.set ("assets/sounds/Music/Puzzle.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Music/Townsong.mp3", "assets/sounds/Music/Townsong.mp3");
			type.set ("assets/sounds/Music/Townsong.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/sounds-go-here.txt", "assets/sounds/sounds-go-here.txt");
			type.set ("assets/sounds/sounds-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/sounds/Tjalle/Back.png", "assets/sounds/Tjalle/Back.png");
			type.set ("assets/sounds/Tjalle/Back.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/Tjalle/Grass Flower 64x64.png", "assets/sounds/Tjalle/Grass Flower 64x64.png");
			type.set ("assets/sounds/Tjalle/Grass Flower 64x64.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/Tjalle/NewRoadTiles.png", "assets/sounds/Tjalle/NewRoadTiles.png");
			type.set ("assets/sounds/Tjalle/NewRoadTiles.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/Tjalle/Police.png", "assets/sounds/Tjalle/Police.png");
			type.set ("assets/sounds/Tjalle/Police.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/Tjalle/Schooltile.png", "assets/sounds/Tjalle/Schooltile.png");
			type.set ("assets/sounds/Tjalle/Schooltile.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/Tjalle/Trashcan.png", "assets/sounds/Tjalle/Trashcan.png");
			type.set ("assets/sounds/Tjalle/Trashcan.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/Tjalle/Water.png", "assets/sounds/Tjalle/Water.png");
			type.set ("assets/sounds/Tjalle/Water.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/beep.ogg", "assets/sounds/beep.ogg");
			type.set ("assets/sounds/beep.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/flixel.ogg", "assets/sounds/flixel.ogg");
			type.set ("assets/sounds/flixel.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			
			
			initialized = true;
			
		} //!initialized
		
	} //initialize
	
	
} //AssetData
