package lime;


import lime.utils.Assets;


class AssetData {

	private static var initialized:Bool = false;
	
	public static var library = new #if haxe3 Map <String, #else Hash <#end LibraryType> ();
	public static var path = new #if haxe3 Map <String, #else Hash <#end String> ();
	public static var type = new #if haxe3 Map <String, #else Hash <#end AssetType> ();	
	
	public static function initialize():Void {
		
		if (!initialized) {
			
			path.set ("assets/data/BaseMap.oel", "assets/data/BaseMap.oel");
			type.set ("assets/data/BaseMap.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/basemap1.oel", "assets/data/basemap1.oel");
			type.set ("assets/data/basemap1.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/basemap2.oel", "assets/data/basemap2.oel");
			type.set ("assets/data/basemap2.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/data-goes-here.txt", "assets/data/data-goes-here.txt");
			type.set ("assets/data/data-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/level_1.oel", "assets/data/level_1.oel");
			type.set ("assets/data/level_1.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/level_2.oel", "assets/data/level_2.oel");
			type.set ("assets/data/level_2.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/level_3.oel", "assets/data/level_3.oel");
			type.set ("assets/data/level_3.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/level_4.oel", "assets/data/level_4.oel");
			type.set ("assets/data/level_4.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/Mission1_0.oel", "assets/data/Mission1_0.oel");
			type.set ("assets/data/Mission1_0.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/Mission1_1.oel", "assets/data/Mission1_1.oel");
			type.set ("assets/data/Mission1_1.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/reachtshelden.oep", "assets/data/reachtshelden.oep");
			type.set ("assets/data/reachtshelden.oep", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/room-001.oel", "assets/data/room-001.oel");
			type.set ("assets/data/room-001.oel", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/AngryDad.png", "assets/images/AngryDad.png");
			type.set ("assets/images/AngryDad.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/BaldMission1.png", "assets/images/BaldMission1.png");
			type.set ("assets/images/BaldMission1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/button.png", "assets/images/button.png");
			type.set ("assets/images/button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/CharacterTilesheet768x768.png", "assets/images/CharacterTilesheet768x768.png");
			type.set ("assets/images/CharacterTilesheet768x768.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/coin.png", "assets/images/coin.png");
			type.set ("assets/images/coin.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/CollectingSpirit Kopie.png", "assets/images/CollectingSpirit Kopie.png");
			type.set ("assets/images/CollectingSpirit Kopie.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/enemy-0.png", "assets/images/enemy-0.png");
			type.set ("assets/images/enemy-0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/enemy-1.png", "assets/images/enemy-1.png");
			type.set ("assets/images/enemy-1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/enemy-2.png", "assets/images/enemy-2.png");
			type.set ("assets/images/enemy-2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Furniture.png", "assets/images/Furniture.png");
			type.set ("assets/images/Furniture.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/girlMission1.png", "assets/images/girlMission1.png");
			type.set ("assets/images/girlMission1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/health.png", "assets/images/health.png");
			type.set ("assets/images/health.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/images-go-here.txt", "assets/images/images-go-here.txt");
			type.set ("assets/images/images-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/images/ion.png", "assets/images/ion.png");
			type.set ("assets/images/ion.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Mission1Girl.png", "assets/images/Mission1Girl.png");
			type.set ("assets/images/Mission1Girl.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Mission2Football.png", "assets/images/Mission2Football.png");
			type.set ("assets/images/Mission2Football.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Mission3Emokid.png", "assets/images/Mission3Emokid.png");
			type.set ("assets/images/Mission3Emokid.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/NPCCharacterTilesheet.png", "assets/images/NPCCharacterTilesheet.png");
			type.set ("assets/images/NPCCharacterTilesheet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pat.png", "assets/images/pat.png");
			type.set ("assets/images/pat.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/player.png", "assets/images/player.png");
			type.set ("assets/images/player.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/pointer.png", "assets/images/pointer.png");
			type.set ("assets/images/pointer.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/SChool modified.png", "assets/images/SChool modified.png");
			type.set ("assets/images/SChool modified.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/street.PNG", "assets/images/street.PNG");
			type.set ("assets/images/street.PNG", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/SWAG-Kid-Walk-Kopie.png", "assets/images/SWAG-Kid-Walk-Kopie.png");
			type.set ("assets/images/SWAG-Kid-Walk-Kopie.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tec.png", "assets/images/tec.png");
			type.set ("assets/images/tec.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/tiles.png", "assets/images/tiles.png");
			type.set ("assets/images/tiles.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Tilesheet_Complete.png", "assets/images/Tilesheet_Complete.png");
			type.set ("assets/images/Tilesheet_Complete.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/Tilesheet_Complete.psd", "assets/images/Tilesheet_Complete.psd");
			type.set ("assets/images/Tilesheet_Complete.psd", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/music/music-goes-here.txt", "assets/music/music-goes-here.txt");
			type.set ("assets/music/music-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/music/select.wav", "assets/music/select.wav");
			type.set ("assets/music/select.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/music/townMusic.wav", "assets/music/townMusic.wav");
			type.set ("assets/music/townMusic.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Heal.mp3", "assets/sounds/Abilities/Heal.mp3");
			type.set ("assets/sounds/Abilities/Heal.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Heal1.mp3", "assets/sounds/Abilities/Heal1.mp3");
			type.set ("assets/sounds/Abilities/Heal1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/PatIndoor.mp3", "assets/sounds/Abilities/PatIndoor.mp3");
			type.set ("assets/sounds/Abilities/PatIndoor.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/PatIndoor2.mp3", "assets/sounds/Abilities/PatIndoor2.mp3");
			type.set ("assets/sounds/Abilities/PatIndoor2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/PatKnigthmare.mp3", "assets/sounds/Abilities/PatKnigthmare.mp3");
			type.set ("assets/sounds/Abilities/PatKnigthmare.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/PatKnigthmare1.mp3", "assets/sounds/Abilities/PatKnigthmare1.mp3");
			type.set ("assets/sounds/Abilities/PatKnigthmare1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/PatOutdoor.mp3", "assets/sounds/Abilities/PatOutdoor.mp3");
			type.set ("assets/sounds/Abilities/PatOutdoor.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/PatOutdoor1.mp3", "assets/sounds/Abilities/PatOutdoor1.mp3");
			type.set ("assets/sounds/Abilities/PatOutdoor1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Shield.mp3", "assets/sounds/Abilities/Shield.mp3");
			type.set ("assets/sounds/Abilities/Shield.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Shield1.mp3", "assets/sounds/Abilities/Shield1.mp3");
			type.set ("assets/sounds/Abilities/Shield1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/1.mp3", "assets/sounds/Abilities/Source/1.mp3");
			type.set ("assets/sounds/Abilities/Source/1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/2.mp3", "assets/sounds/Abilities/Source/2.mp3");
			type.set ("assets/sounds/Abilities/Source/2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/3.mp3", "assets/sounds/Abilities/Source/3.mp3");
			type.set ("assets/sounds/Abilities/Source/3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/Heal.wav", "assets/sounds/Abilities/Source/Heal.wav");
			type.set ("assets/sounds/Abilities/Source/Heal.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/Heal1.wav", "assets/sounds/Abilities/Source/Heal1.wav");
			type.set ("assets/sounds/Abilities/Source/Heal1.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/Hit_Hurt18.wav", "assets/sounds/Abilities/Source/Hit_Hurt18.wav");
			type.set ("assets/sounds/Abilities/Source/Hit_Hurt18.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/Hit_Hurt32.wav", "assets/sounds/Abilities/Source/Hit_Hurt32.wav");
			type.set ("assets/sounds/Abilities/Source/Hit_Hurt32.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/JUDGE-O-METERCOIN.wav", "assets/sounds/Abilities/Source/JUDGE-O-METERCOIN.wav");
			type.set ("assets/sounds/Abilities/Source/JUDGE-O-METERCOIN.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/Push.wav", "assets/sounds/Abilities/Source/Push.wav");
			type.set ("assets/sounds/Abilities/Source/Push.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/Push1.wav", "assets/sounds/Abilities/Source/Push1.wav");
			type.set ("assets/sounds/Abilities/Source/Push1.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Abilities/Source/Shield1.wav", "assets/sounds/Abilities/Source/Shield1.wav");
			type.set ("assets/sounds/Abilities/Source/Shield1.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Game/JUDGE-O-METERCOIN.mp3", "assets/sounds/Game/JUDGE-O-METERCOIN.mp3");
			type.set ("assets/sounds/Game/JUDGE-O-METERCOIN.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Game/select-1.wav", "assets/sounds/Game/select-1.wav");
			type.set ("assets/sounds/Game/select-1.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Gesprek1.wav", "assets/sounds/Gesprek1.wav");
			type.set ("assets/sounds/Gesprek1.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/IntroMissie/1IntroPijltjestoetsen.mp3", "assets/sounds/IntroMissie/1IntroPijltjestoetsen.mp3");
			type.set ("assets/sounds/IntroMissie/1IntroPijltjestoetsen.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/IntroMissie/2GoedGedaan.mp3", "assets/sounds/IntroMissie/2GoedGedaan.mp3");
			type.set ("assets/sounds/IntroMissie/2GoedGedaan.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/IntroMissie/3PatInstructie.mp3", "assets/sounds/IntroMissie/3PatInstructie.mp3");
			type.set ("assets/sounds/IntroMissie/3PatInstructie.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/IntroMissie/4TecInstructie1.mp3", "assets/sounds/IntroMissie/4TecInstructie1.mp3");
			type.set ("assets/sounds/IntroMissie/4TecInstructie1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/IntroMissie/5TecInstructie2.mp3", "assets/sounds/IntroMissie/5TecInstructie2.mp3");
			type.set ("assets/sounds/IntroMissie/5TecInstructie2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/IntroMissie/6ProfInstructie.mp3", "assets/sounds/IntroMissie/6ProfInstructie.mp3");
			type.set ("assets/sounds/IntroMissie/6ProfInstructie.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/IntroMissie/7IntroOutro.mp3", "assets/sounds/IntroMissie/7IntroOutro.mp3");
			type.set ("assets/sounds/IntroMissie/7IntroOutro.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/IntroVoice.mp3", "assets/sounds/IntroVoice.mp3");
			type.set ("assets/sounds/IntroVoice.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Gesprek1.mp3", "assets/sounds/Missie1/Gesprek1.mp3");
			type.set ("assets/sounds/Missie1/Gesprek1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind1/Prof1-4.mp3", "assets/sounds/Missie1/Kind1/Prof1-4.mp3");
			type.set ("assets/sounds/Missie1/Kind1/Prof1-4.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind1/Prof2-4.mp3", "assets/sounds/Missie1/Kind1/Prof2-4.mp3");
			type.set ("assets/sounds/Missie1/Kind1/Prof2-4.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind1/Prof3-4.mp3", "assets/sounds/Missie1/Kind1/Prof3-4.mp3");
			type.set ("assets/sounds/Missie1/Kind1/Prof3-4.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind2/Prof1-1.mp3", "assets/sounds/Missie1/Kind2/Prof1-1.mp3");
			type.set ("assets/sounds/Missie1/Kind2/Prof1-1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind2/Prof2-1.mp3", "assets/sounds/Missie1/Kind2/Prof2-1.mp3");
			type.set ("assets/sounds/Missie1/Kind2/Prof2-1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind2/Prof3-1.mp3", "assets/sounds/Missie1/Kind2/Prof3-1.mp3");
			type.set ("assets/sounds/Missie1/Kind2/Prof3-1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind3/Prof1-2.mp3", "assets/sounds/Missie1/Kind3/Prof1-2.mp3");
			type.set ("assets/sounds/Missie1/Kind3/Prof1-2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind3/Prof2-2.mp3", "assets/sounds/Missie1/Kind3/Prof2-2.mp3");
			type.set ("assets/sounds/Missie1/Kind3/Prof2-2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind3/Prof3-2.mp3", "assets/sounds/Missie1/Kind3/Prof3-2.mp3");
			type.set ("assets/sounds/Missie1/Kind3/Prof3-2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Kind3/Prof4-2.mp3", "assets/sounds/Missie1/Kind3/Prof4-2.mp3");
			type.set ("assets/sounds/Missie1/Kind3/Prof4-2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Prof4-3.mp3", "assets/sounds/Missie1/Prof4-3.mp3");
			type.set ("assets/sounds/Missie1/Prof4-3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Test/Prof1-3.mp3", "assets/sounds/Missie1/Test/Prof1-3.mp3");
			type.set ("assets/sounds/Missie1/Test/Prof1-3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Test/Prof2-3.mp3", "assets/sounds/Missie1/Test/Prof2-3.mp3");
			type.set ("assets/sounds/Missie1/Test/Prof2-3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Test/Prof3-3.mp3", "assets/sounds/Missie1/Test/Prof3-3.mp3");
			type.set ("assets/sounds/Missie1/Test/Prof3-3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Test/Teacher1.mp3", "assets/sounds/Missie1/Test/Teacher1.mp3");
			type.set ("assets/sounds/Missie1/Test/Teacher1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie1/Test/Teacher2.mp3", "assets/sounds/Missie1/Test/Teacher2.mp3");
			type.set ("assets/sounds/Missie1/Test/Teacher2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Dad1.mp3", "assets/sounds/Missie2/Dad1.mp3");
			type.set ("assets/sounds/Missie2/Dad1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Dad2.mp3", "assets/sounds/Missie2/Dad2.mp3");
			type.set ("assets/sounds/Missie2/Dad2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Dad3.mp3", "assets/sounds/Missie2/Dad3.mp3");
			type.set ("assets/sounds/Missie2/Dad3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Prof1.mp3", "assets/sounds/Missie2/Prof1.mp3");
			type.set ("assets/sounds/Missie2/Prof1.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Prof2.mp3", "assets/sounds/Missie2/Prof2.mp3");
			type.set ("assets/sounds/Missie2/Prof2.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Prof3.mp3", "assets/sounds/Missie2/Prof3.mp3");
			type.set ("assets/sounds/Missie2/Prof3.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Prof4.mp3", "assets/sounds/Missie2/Prof4.mp3");
			type.set ("assets/sounds/Missie2/Prof4.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Missie2/Prof5.mp3", "assets/sounds/Missie2/Prof5.mp3");
			type.set ("assets/sounds/Missie2/Prof5.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Music/Chase.mp3", "assets/sounds/Music/Chase.mp3");
			type.set ("assets/sounds/Music/Chase.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Music/Haahn's Dutch.wav", "assets/sounds/Music/Haahn's Dutch.wav");
			type.set ("assets/sounds/Music/Haahn's Dutch.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Music/Lab Junk.wav", "assets/sounds/Music/Lab Junk.wav");
			type.set ("assets/sounds/Music/Lab Junk.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/Music/Puzzle.mp3", "assets/sounds/Music/Puzzle.mp3");
			type.set ("assets/sounds/Music/Puzzle.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/Music/Townsong.mp3", "assets/sounds/Music/Townsong.mp3");
			type.set ("assets/sounds/Music/Townsong.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/sounds/sounds-go-here.txt", "assets/sounds/sounds-go-here.txt");
			type.set ("assets/sounds/sounds-go-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/sounds/Tjalle/Back.png", "assets/sounds/Tjalle/Back.png");
			type.set ("assets/sounds/Tjalle/Back.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/Tjalle/Grass Flower 64x64.png", "assets/sounds/Tjalle/Grass Flower 64x64.png");
			type.set ("assets/sounds/Tjalle/Grass Flower 64x64.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/Tjalle/NewRoadTiles.png", "assets/sounds/Tjalle/NewRoadTiles.png");
			type.set ("assets/sounds/Tjalle/NewRoadTiles.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/Tjalle/Police.png", "assets/sounds/Tjalle/Police.png");
			type.set ("assets/sounds/Tjalle/Police.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/Tjalle/Schooltile.png", "assets/sounds/Tjalle/Schooltile.png");
			type.set ("assets/sounds/Tjalle/Schooltile.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/Tjalle/Trashcan.png", "assets/sounds/Tjalle/Trashcan.png");
			type.set ("assets/sounds/Tjalle/Trashcan.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/Tjalle/Water.png", "assets/sounds/Tjalle/Water.png");
			type.set ("assets/sounds/Tjalle/Water.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/sounds/beep.ogg", "assets/sounds/beep.ogg");
			type.set ("assets/sounds/beep.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/flixel.ogg", "assets/sounds/flixel.ogg");
			type.set ("assets/sounds/flixel.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			
			
			initialized = true;
			
		} //!initialized
		
	} //initialize
	
	
} //AssetData
